# Generated by Django 4.1.1 on 2024-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amonic", "0006_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
