# Generated by Django 4.1.1 on 2024-09-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("amonic", "0008_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
