# Generated by Django 4.1.1 on 2024-09-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amonic", "0010_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
