# Generated by Django 4.1.1 on 2024-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amonic", "0012_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
